/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ofyevfyfinzdpjqrmbuv"
export const supabaseUrl = `https://${projectId}.supabase.co`
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9meWV2ZnlmaW56ZHBqcXJtYnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5NDU0MjYsImV4cCI6MjEwMjUyMTQyNn0.4ISResmA0qdELbWLtyXuGZmWCrgEw8203JgiZgN0O8k"